name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 16.13.0
        - name: Install
          run: npm install
        - name: Test
          env:
            BS_USER: ${{secrets.BS_USER}}
            BS_KEY: ${{secrets.BS_KEY}}
          run: npx wdio wdio.bs.android.*
        - uses: actions/upload-artifact@v1
          with:
            name: allure-report
            path: ./allure-report
          with:
            name: allure-results
            path: ./allure-results
